### ISSUE TITLE
Only works with msysgit, but not with Git For Windows (https://github.com/git-for-windows/git)

### ISSUE THREAD

**Issue by MagicAndre1981** [pocorall/scm-notifier#19]
Because I see no progress with msysgit, I tried Git For Windows (https://github.com/git-for-windows/git). But here the status icons are always gray but I see that Git was called and checked the repositories.

Can you please look at this and try to make it compatible?

**Comment by pocorall** [comment]
I've tested it with [Git-for-Windows 2.4.6 RC5](https://github.com/git-for-windows/git/releases/tag/v2.4.6.windows.1) and current master of scm-notifier. It seems working fine with proper icons.

Would you describe more specifically how to reproduce it?

**Comment by MagicAndre1981** [comment]
I also use this version. The issue is that the tool runs git to check the status, but the status is not updated and the icon is gray. When I change the git.exe to the older msysgit one I see the status update immediately.

**Comment by pocorall** [comment]
I still can't reproduce this issue. There might be some changes on display of Git for Windows. Will you take a look at exactly which part of difference makes the problem? Submitting pull request would much better.

**Comment by MagicAndre1981** [comment]
ok, I think I found the cause.
```ScmRepositoryStatus GetStatus()``` returns ```ScmRepositoryStatus.Unknown``` because the new git return string in German (my main language set in Windows) and your tool parses English texts.

**Comment by MagicAndre1981** [comment]
What is your language setting? Do you use Korean or En-US MUI?

**Comment by pocorall** [comment]
My git prints English. Can you make some patch for internationalization? All of the string resources parsing git are in `GitRepository.cs`.

**Comment by MagicAndre1981** [comment]
with the latest version (2.7) it works now fine.
