### ISSUE TITLE
Can't start SCM_Notifier after failed Settings import

### ISSUE THREAD

**Issue by bobson83** [pocorall/scm-notifier#24]
I have export my old settings from svn_notifier and  i have tried to import this settings in SCM_Notifier. That's failed. After Computer restart,if i want to start SCM Notifier, then i get a Error Window with  System.ApplicationException: INI-file migration code is incomplete
 bei pocorall.SCM_Notifier.Config.MigrateIfNecessary()
 bei pocorall.SCM_Notifier.Config.Init()
 bei pocorall.SCM_Notifier.Config.Init(String fileName) 
 bei pocorall.SCM_Notifier.MainForm.Main(String[] args)

Any ideas, how i can handle this?

**Comment by pocorall** [comment]
Remove `scm-notifier.ini` file. it is under `Users\user-name\AppData\Roaming\scm-notifier`.

**Comment by bobson83** [comment]
@pocorall Joap, thx, thats works.
