### ISSUE TITLE
INI file is created in the root of the AppData folder

### ISSUE THREAD

**Issue by Guddler** [pocorall/scm-notifier#9]
I believe it should really be in a sub folder, typically this folder would be called: TOCPlus.com

```
diff --git a/SCM_Notifier/MainForm.cs b/SCM_Notifier/MainForm.cs
index 333e8a1..9b25479 100644
--- a/SCM_Notifier/MainForm.cs
+++ b/SCM_Notifier/MainForm.cs
 
@@ -1357,12 +1361,20 @@ namespace pocorall.SCM_Notifier
 				}
 
 				const string iniFileName = "SCM_Notifier.ini";
-				if (File.Exists (iniFileName))
-					Config.Init (iniFileName);
-				else
-					Config.Init (Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.ApplicationData), iniFileName));
+                if (File.Exists(iniFileName))
+                {
+                    Config.Init(iniFileName);
+                }
+                else
+                {
+                    // MW: Ensure INI file is created in subdirectory of AppData folder
+                    if (!File.Exists(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), @"TOCPlus.com\SCMNotifier")))
+                        Directory.CreateDirectory(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), @"TOCPlus.com\SCMNotifier"));
+
+                    Config.Init(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), @"TOCPlus.com\SCMNotifier\" + iniFileName));
+                }
 
-				if (!Config.IsSettingsOK())
+			    if (!Config.IsSettingsOK())
 					if (new SettingsForm().ShowDialog() != DialogResult.OK)
 						return;
```

**Comment by regisbsb** [comment]
What TOCPlus????
It should be SCMNotifier. Could you provide a merge request?

**Comment by Guddler** [comment]
Sorry, this was a year and a half ago now! I don't work in the same job any more, or use SCMNotifier any more. As for TOCPlus, I would assume that was my guess at what the company was? I could easily have been doing too many things at once however :)

The point to all of this is that the INI file wants to live in a subfolder off of APPDATA related to first company and then product: %APPDATA%\<Company>\<Product>, if no company because the entity is an individual then just the product name would probably suffice but I would probably use my own name as the company.

**Comment by regisbsb** [comment]
I understand. Would you still be interested in forking the project and
providing a pull request?

**Comment by pocorall** [comment]
Now I fixed it.

**Comment by regisbsb** [comment]
Thanks @pocorall , I was asking @Guddler but given you put all the effort and already merged then it's all good!!! I love open source!

**Comment by pocorall** [comment]
I realized that existing users who has `SCM_Notifier.ini` file would confused when they update our program because all of the repository configuration is suddenly not appeared.

There should be some migration code before release.

**Comment by pocorall** [comment]
The commit https://github.com/pocorall/scm-notifier/commit/8e172a78fb059580548ca20b2abf66cdeb67b84b fixes this.
